### ISSUE TITLE
After install Binance via HACS I see those errors in HA log

### ISSUE THREAD

**Issue by poudenes** [Kartax/home-assistant-binance#1]
Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest
```
- platform: binance
  symbols:
    - BTCUSDT
    - ETHUSDT
    - XRPUSDT
    - SHIBUSDT
    - LUNCUSDT
    - LUNAUSDT
```
SHIBUSDT get a state value of: `1.274e-05`
Attributes:
```
symbol: SHIBUSDT
priceChange: 0.00000033
priceChangePercent: 2.659
weightedAvgPrice: 0.00001274
openPrice: 0.00001241
highPrice: 0.00001318
lowPrice: 0.00001236
lastPrice: 0.00001274
volume: 2942211928721.00
quoteVolume: 37480409.81301160
openTime: 1677396660000
closeTime: 1677483062740
firstId: 360330986
lastId: 360411696
count: 80711
device_class: monetary
friendly_name: Binance Ticker SHIBUSDT
```
 
```
2023-02-27 08:27:31.369 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: BinanceTickerSensor.update() takes 1 positional argument but 2 were given
2023-02-27 08:27:31.704 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: BinanceTickerSensor.update() takes 1 positional argument but 2 were given
2023-02-27 08:27:34.287 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: BinanceTickerSensor.update() takes 1 positional argument but 2 were given
2023-02-27 08:27:34.830 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: BinanceTickerSensor.update() takes 1 positional argument but 2 were given
2023-02-27 08:27:35.379 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: BinanceTickerSensor.update() takes 1 positional argument but 2 were given
2023-02-27 08:27:35.924 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
```

**Comment by Kartax** [comment]
I will take care of the werid value-conversion(SHIBUSDT get a state value of: 1.274e-05)

But the error i cannot reproduce so far. Seems not to be relatedto value-conversion.

**Comment by poudenes** [comment]
I have now only:
```
- platform: binance
  symbols:
    - BTCUSDT
```
and get now even less errors. So it is something related to the integration.
Was trying to set log level to debug specific for this but wasn't able to do

**Comment by Kartax** [comment]
State value decimals will now be displayed correctly (like for example **0.00001209** )

Regarding the error stacktrace: Please create a separate issue if it appears again.
