### ISSUE TITLE
BinanceTickerSensor.update() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by poudenes** [Kartax/home-assistant-binance#2]
After HA restart I see those errors very minute:

```
Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

Binance Integration Version: 1.1.1
```

```
2023-03-01 14:21:06.964 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: BinanceTickerSensor.update() takes 1 positional argument but 2 were given
2023-03-01 14:22:07.002 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: BinanceTickerSensor.update() takes 1 positional argument but 2 were given
2023-03-01 14:23:06.965 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: BinanceTickerSensor.update() takes 1 positional argument but 2 were given
```

**Comment by Kartax** [comment]
fixed with vertsion 1.1.2
